version: '3.9'

services:


  auth_app:
    container_name: auth_app
    build:
      context: .
      dockerfile: Dockerfile
 
    environment:
      - SECRET_KEY1="qwertyuiopasdfghjklzxcvbnmgenratedfjsdfjs"

    volumes:
      - .:/usr/src/app

    ports:  
      - "80:80"
      - "443:80"
      - "5678:5678"